"""Process-level validation for semantic traces (DSL-era simplified version).

Original v0 implementation contained 5500+ lines of family-specific validators
(process_families/*) that verified each algorithm's invariants by re-computing
expected dp values, BFS distances, KMP failure tables, etc. With the DSL-based
architecture this is no longer needed: the trace is produced by executing
DSL-instrumented Python code in a sandbox, so schema correctness and per-step
state consistency are guaranteed by construction.

This module preserves the external API for backward compatibility with
pipeline.py / degradation.py / repair_context.py callers, but performs only
the lightest sanity checks (schema-level invariants are already enforced by
SemanticTrace.model_validate upstream).
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any, Literal

from algolab.compiler.target_parser import parse_target
from algolab.schemas.semantic_trace import SemanticEvent, SemanticOp, SemanticTrace


# -----------------------------------------------------------------------------
# Public types and level constants (preserved for callers)
# -----------------------------------------------------------------------------

ProcessInvariantLevel = Literal["core", "structure", "algorithm", "all"]
ProcessValidationStatus = Literal["strong", "fallback"]

CORE_LEVEL: ProcessInvariantLevel = "core"
STRUCTURE_LEVEL: ProcessInvariantLevel = "structure"
ALGORITHM_LEVEL: ProcessInvariantLevel = "algorithm"
ALL_LEVEL: ProcessInvariantLevel = "all"
DEFAULT_PROCESS_LEVELS: tuple[ProcessInvariantLevel, ...] = (
    CORE_LEVEL,
    STRUCTURE_LEVEL,
    ALGORITHM_LEVEL,
)


@dataclass(frozen=True)
class ProcessFamilyRegistration:
    family: str
    label: str
    status: ProcessValidationStatus
    level: ProcessInvariantLevel
    coverage_rule: str
    failure_type: str
    checks: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()


# -----------------------------------------------------------------------------
# Registry: minimal stubs (DSL-era no longer maintains per-family validators)
# -----------------------------------------------------------------------------

_DSL_COVERAGE_RULE = "DSL-era: trace is generated by executing DSL-instrumented code in a sandbox; schema correctness is enforced by construction"

_FAMILY_LABELS = {
    "dp_1d": "一维 DP", "dp_2d": "二维 DP", "dp_core": "DP 核心扩展",
    "binary_search": "二分", "array_pointer": "数组指针 / 窗口 / 前缀",
    "basic_graph": "BFS/DFS 基础图", "shortest_path_mst": "最短路 / MST",
    "string_advanced": "字符串高级算法", "hash_map": "哈希表 / map",
    "monotonic_stack": "栈 / 队列 / 单调栈", "sorting": "排序",
    "linked_list_cache": "链表与缓存", "greedy": "贪心",
    "tree_bst_lca": "树 / BST / LCA", "tree_dp": "树形 DP",
    "heap_topk_huffman": "堆 / TopK / Huffman", "trie": "Trie",
    "union_find": "并查集", "backtracking_recursion": "回溯 / 递归",
    "geometry_sweep": "几何 / 扫描线", "range_structure": "区间结构",
    "math_bit": "数学与位运算", "advanced_graph": "图高级",
}

PROCESS_VALIDATION_REGISTRY: tuple[ProcessFamilyRegistration, ...] = tuple(
    ProcessFamilyRegistration(
        family=key,
        label=label,
        status="strong",  # all families covered uniformly by DSL guarantees
        level=ALGORITHM_LEVEL,
        coverage_rule=_DSL_COVERAGE_RULE,
        failure_type="process_invariant",
        aliases=(key, label, key.replace("_", " ")),
    )
    for key, label in _FAMILY_LABELS.items()
)

_UNCOVERED_PROCESS_PROFILE = ProcessFamilyRegistration(
    family="uncovered",
    label="未覆盖算法族",
    status="fallback",
    level=CORE_LEVEL,
    coverage_rule=_DSL_COVERAGE_RULE,
    failure_type="process_uncovered",
)

_EXPLICIT_PROCESS_FAILURE_TYPES = {
    "process_invariant",
    "coverage_error",
    "process_fallback",
    "process_uncovered",
}


# -----------------------------------------------------------------------------
# Public functions
# -----------------------------------------------------------------------------

def process_validation_registry() -> tuple[ProcessFamilyRegistration, ...]:
    return PROCESS_VALIDATION_REGISTRY


def process_validation_profile_for_family(family: str | None) -> ProcessFamilyRegistration:
    key = _normalize_family_name(family or "")
    if not key:
        return _UNCOVERED_PROCESS_PROFILE
    for profile in PROCESS_VALIDATION_REGISTRY:
        candidates = (profile.family, profile.label, *profile.aliases)
        if any(_family_alias_matches(key, candidate) for candidate in candidates):
            return profile
    return _UNCOVERED_PROCESS_PROFILE


def process_validation_profile_for_trace(trace: SemanticTrace) -> ProcessFamilyRegistration:
    """Best-effort family inference from trace.algorithm; uncovered if unknown."""
    return process_validation_profile_for_family(getattr(trace, "algorithm", None))


def process_failure_type_for_message(message: str) -> str | None:
    """Return one of the explicit process failure types if the message names it.

    DSL-era simplification: we no longer keyword-match algorithm names; the
    only signals we trust are explicit failure_type=... markers and a small
    set of core process keywords.
    """
    text = message.lower()
    explicit = _explicit_failure_type(text)
    if explicit in _EXPLICIT_PROCESS_FAILURE_TYPES:
        return explicit
    if "trace coverage" in text or "coverage" in text or "覆盖率" in message:
        return "coverage_error"
    if "process_uncovered" in text or "未注册算法族" in message:
        return "process_uncovered"
    if "process invariant" in text or "process_invariant" in text:
        return "process_invariant"
    return None


def validate_process(
    trace: SemanticTrace,
    levels: ProcessInvariantLevel | Iterable[ProcessInvariantLevel] | None = None,
) -> tuple[list[str], list[str]]:
    """Validate DSL-level causal invariants without algorithm-specific rules.

    These checks only depend on guarantees made by ``TraceSession``: creates
    precede later uses, state snapshots are post-event snapshots, explicit
    before/after values agree with adjacent snapshots, and enter/exit events are
    properly nested. They intentionally do not reimplement per-family oracles.
    """
    _ = _normalize_levels(levels)
    if not isinstance(trace, SemanticTrace):
        return ([f"validate_process: 参数不是 SemanticTrace（{type(trace).__name__}）"], [])

    errors: list[str] = []
    warnings: list[str] = []
    previous_state: dict[str, Any] = {}
    frame_stack: list[str] = []
    answer_seen = False

    for event in trace.events:
        targets = [target.id for target in event.targets]
        frame_targets = [target for target in targets if target.startswith("frame:")]

        if event.op == SemanticOp.CREATE and answer_seen:
            errors.append(f"第 {event.step} 步在答案事件之后创建对象，违反因果顺序")

        if event.op != SemanticOp.CREATE:
            _validate_ordered_references(event, previous_state, errors)

        _validate_explicit_transition(event, previous_state, errors)

        if event.op == SemanticOp.ENTER:
            frame_stack.extend(frame_targets)
        elif event.op == SemanticOp.EXIT:
            for target in frame_targets:
                if not frame_stack:
                    errors.append(f"第 {event.step} 步 exit 缺少对应 enter：{target}")
                    continue
                expected = frame_stack[-1]
                if target != expected:
                    errors.append(
                        f"第 {event.step} 步阶段退出顺序错误：期望 {expected}，实际 {target}"
                    )
                    continue
                frame_stack.pop()

        if _is_answer_event(event):
            answer_seen = True
        previous_state = event.state

    if frame_stack:
        warnings.append(f"trace 结束时仍有 {len(frame_stack)} 个未闭合阶段，可能由 max_events 截断")

    return errors, warnings


def _validate_ordered_references(
    event: SemanticEvent,
    previous_state: dict[str, Any],
    errors: list[str],
) -> None:
    references = list(event.deps)
    if event.op in {
        SemanticOp.SET,
        SemanticOp.MOVE,
        SemanticOp.LINK,
        SemanticOp.UNLINK,
        SemanticOp.PUSH,
        SemanticOp.POP,
    }:
        references.extend(event.targets)
    for ref in references:
        if ref.id in {"answer", "result"}:
            continue
        if "." in ref.id or "->" in ref.id:
            continue
        parsed = parse_target(ref.id)
        if parsed.kind in {"node", "edge", "frame", "point", "char", "slice"}:
            continue
        previous_exists, _previous_value = _resolve_state_target(previous_state, ref.id)
        current_exists, _current_value = _resolve_state_target(event.state, ref.id)
        if not previous_exists and not current_exists:
            label = "dependency" if ref in event.deps else "target"
            errors.append(f"第 {event.step} 步 {label} 在使用前不可解析：{ref.id}")


def _validate_explicit_transition(
    event: SemanticEvent,
    previous_state: dict[str, Any],
    errors: list[str],
) -> None:
    if len(event.targets) != 1:
        return
    target = event.targets[0].id
    fields = event.model_fields_set
    previous_exists, previous_value = _resolve_state_target(previous_state, target)
    current_exists, current_value = _resolve_state_target(event.state, target)

    if "before" in fields and event.before is not None and previous_exists:
        if previous_value != event.before:
            errors.append(
                f"第 {event.step} 步 {target} 的 before 与前序状态不一致："
                f"{event.before!r} != {previous_value!r}"
            )
    if "after" in fields and event.after is not None and current_exists:
        if current_value != event.after:
            errors.append(
                f"第 {event.step} 步 {target} 的 after 与当前状态不一致："
                f"{event.after!r} != {current_value!r}"
            )


def _is_answer_event(event: SemanticEvent) -> bool:
    return event.role == "answer"


def _resolve_state_target(state: dict[str, Any], target: str) -> tuple[bool, Any]:
    if target in state:
        return True, state[target]
    if target.startswith("pointer:"):
        name = target.split(":", 1)[1]
        return (name in state, state.get(name))
    if "[" not in target or not target.endswith("]"):
        return False, None

    name, rest = target.split("[", 1)
    if not name or name not in state:
        return False, None
    parts = [part.rstrip("]") for part in rest.split("[")]
    if not parts or any(part == "" or ":" in part for part in parts):
        return False, None

    value: Any = state[name]
    for part in parts:
        if isinstance(value, (list, str)):
            try:
                index = int(part)
            except ValueError:
                return False, None
            if index < -len(value) or index >= len(value):
                return False, None
            value = value[index]
        elif isinstance(value, dict):
            if part in value:
                value = value[part]
            else:
                try:
                    numeric = int(part)
                except ValueError:
                    return False, None
                if numeric not in value:
                    return False, None
                value = value[numeric]
        else:
            return False, None
    return True, value


# -----------------------------------------------------------------------------
# Internal helpers
# -----------------------------------------------------------------------------

def _normalize_levels(
    levels: ProcessInvariantLevel | Iterable[ProcessInvariantLevel] | None,
) -> set[ProcessInvariantLevel]:
    if levels is None:
        return set(DEFAULT_PROCESS_LEVELS)
    requested = {levels} if isinstance(levels, str) else set(levels)
    if not requested:
        return set(DEFAULT_PROCESS_LEVELS)
    valid = set(DEFAULT_PROCESS_LEVELS)
    unknown = requested - valid - {ALL_LEVEL}
    if unknown:
        raise ValueError(f"未知 process invariant 层级：{', '.join(sorted(unknown))}")
    if ALL_LEVEL in requested:
        return set(DEFAULT_PROCESS_LEVELS)
    return requested


def _normalize_family_name(value: str) -> str:
    return " ".join(value.strip().lower().replace("_", " ").split())


def _family_alias_matches(key: str, alias: str) -> bool:
    normalized = _normalize_family_name(alias)
    return bool(normalized) and (key == normalized or normalized in key)


def _explicit_failure_type(text: str) -> str | None:
    marker = "failure_type="
    if marker not in text:
        return None
    tail = text.split(marker, 1)[1]
    value: list[str] = []
    for char in tail:
        if char.islower() or char == "_":
            value.append(char)
        else:
            break
    return "".join(value) or None
