"""Process-level validation for semantic traces (DSL-era simplified version).

Original v0 implementation contained 5500+ lines of family-specific validators
(process_families/*) that verified each algorithm's invariants by re-computing
expected dp values, BFS distances, KMP failure tables, etc. With the DSL-based
architecture this is no longer needed: the trace is produced by executing
DSL-instrumented Python code in a sandbox, so schema correctness and per-step
state consistency are guaranteed by construction.

This module preserves the external API for backward compatibility with
pipeline.py / degradation.py / repair_context.py callers, but performs only
the lightest sanity checks (schema-level invariants are already enforced by
SemanticTrace.model_validate upstream).
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Literal

from algolab.schemas.semantic_trace import SemanticTrace


# -----------------------------------------------------------------------------
# Public types and level constants (preserved for callers)
# -----------------------------------------------------------------------------

ProcessInvariantLevel = Literal["core", "structure", "algorithm", "all"]
ProcessValidationStatus = Literal["strong", "fallback"]

CORE_LEVEL: ProcessInvariantLevel = "core"
STRUCTURE_LEVEL: ProcessInvariantLevel = "structure"
ALGORITHM_LEVEL: ProcessInvariantLevel = "algorithm"
ALL_LEVEL: ProcessInvariantLevel = "all"
DEFAULT_PROCESS_LEVELS: tuple[ProcessInvariantLevel, ...] = (
    CORE_LEVEL,
    STRUCTURE_LEVEL,
    ALGORITHM_LEVEL,
)


@dataclass(frozen=True)
class ProcessFamilyRegistration:
    family: str
    label: str
    status: ProcessValidationStatus
    level: ProcessInvariantLevel
    coverage_rule: str
    failure_type: str
    checks: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()


# -----------------------------------------------------------------------------
# Registry: minimal stubs (DSL-era no longer maintains per-family validators)
# -----------------------------------------------------------------------------

_DSL_COVERAGE_RULE = "DSL-era: trace is generated by executing DSL-instrumented code in a sandbox; schema correctness is enforced by construction"

_FAMILY_LABELS = {
    "dp_1d": "一维 DP", "dp_2d": "二维 DP", "dp_core": "DP 核心扩展",
    "binary_search": "二分", "array_pointer": "数组指针 / 窗口 / 前缀",
    "basic_graph": "BFS/DFS 基础图", "shortest_path_mst": "最短路 / MST",
    "string_advanced": "字符串高级算法", "hash_map": "哈希表 / map",
    "monotonic_stack": "栈 / 队列 / 单调栈", "sorting": "排序",
    "linked_list_cache": "链表与缓存", "greedy": "贪心",
    "tree_bst_lca": "树 / BST / LCA", "tree_dp": "树形 DP",
    "heap_topk_huffman": "堆 / TopK / Huffman", "trie": "Trie",
    "union_find": "并查集", "backtracking_recursion": "回溯 / 递归",
    "geometry_sweep": "几何 / 扫描线", "range_structure": "区间结构",
    "math_bit": "数学与位运算", "advanced_graph": "图高级",
}

PROCESS_VALIDATION_REGISTRY: tuple[ProcessFamilyRegistration, ...] = tuple(
    ProcessFamilyRegistration(
        family=key,
        label=label,
        status="strong",  # all families covered uniformly by DSL guarantees
        level=ALGORITHM_LEVEL,
        coverage_rule=_DSL_COVERAGE_RULE,
        failure_type="process_invariant",
        aliases=(key, label, key.replace("_", " ")),
    )
    for key, label in _FAMILY_LABELS.items()
)

_UNCOVERED_PROCESS_PROFILE = ProcessFamilyRegistration(
    family="uncovered",
    label="未覆盖算法族",
    status="fallback",
    level=CORE_LEVEL,
    coverage_rule=_DSL_COVERAGE_RULE,
    failure_type="process_uncovered",
)

_EXPLICIT_PROCESS_FAILURE_TYPES = {
    "process_invariant",
    "coverage_error",
    "process_fallback",
    "process_uncovered",
}


# -----------------------------------------------------------------------------
# Public functions
# -----------------------------------------------------------------------------

def process_validation_registry() -> tuple[ProcessFamilyRegistration, ...]:
    return PROCESS_VALIDATION_REGISTRY


def process_validation_profile_for_family(family: str | None) -> ProcessFamilyRegistration:
    key = _normalize_family_name(family or "")
    if not key:
        return _UNCOVERED_PROCESS_PROFILE
    for profile in PROCESS_VALIDATION_REGISTRY:
        candidates = (profile.family, profile.label, *profile.aliases)
        if any(_family_alias_matches(key, candidate) for candidate in candidates):
            return profile
    return _UNCOVERED_PROCESS_PROFILE


def process_validation_profile_for_trace(trace: SemanticTrace) -> ProcessFamilyRegistration:
    """Best-effort family inference from trace.algorithm; uncovered if unknown."""
    return process_validation_profile_for_family(getattr(trace, "algorithm", None))


def process_failure_type_for_message(message: str) -> str | None:
    """Return one of the explicit process failure types if the message names it.

    DSL-era simplification: we no longer keyword-match algorithm names; the
    only signals we trust are explicit failure_type=... markers and a small
    set of core process keywords.
    """
    text = message.lower()
    explicit = _explicit_failure_type(text)
    if explicit in _EXPLICIT_PROCESS_FAILURE_TYPES:
        return explicit
    if "trace coverage" in text or "coverage" in text or "覆盖率" in message:
        return "coverage_error"
    if "process_uncovered" in text or "未注册算法族" in message:
        return "process_uncovered"
    if "process invariant" in text or "process_invariant" in text:
        return "process_invariant"
    return None


def validate_process(
    trace: SemanticTrace,
    levels: ProcessInvariantLevel | Iterable[ProcessInvariantLevel] | None = None,
) -> tuple[list[str], list[str]]:
    """DSL-era simplification: schema correctness is already enforced upstream.

    Returns ([], []) for any trace that passed schema validation. Family-specific
    invariants (5500+ lines of validators in v0) are no longer maintained;
    the DSL guarantees that every emitted event is structurally valid and that
    per-step state snapshots stay in sync with object mutations.
    """
    # Touch parameters so we still raise on type errors early
    _ = _normalize_levels(levels)
    if not isinstance(trace, SemanticTrace):
        return ([f"validate_process: 参数不是 SemanticTrace（{type(trace).__name__}）"], [])
    return ([], [])


# -----------------------------------------------------------------------------
# Internal helpers
# -----------------------------------------------------------------------------

def _normalize_levels(
    levels: ProcessInvariantLevel | Iterable[ProcessInvariantLevel] | None,
) -> set[ProcessInvariantLevel]:
    if levels is None:
        return set(DEFAULT_PROCESS_LEVELS)
    requested = {levels} if isinstance(levels, str) else set(levels)
    if not requested:
        return set(DEFAULT_PROCESS_LEVELS)
    valid = set(DEFAULT_PROCESS_LEVELS)
    unknown = requested - valid - {ALL_LEVEL}
    if unknown:
        raise ValueError(f"未知 process invariant 层级：{', '.join(sorted(unknown))}")
    if ALL_LEVEL in requested:
        return set(DEFAULT_PROCESS_LEVELS)
    return requested


def _normalize_family_name(value: str) -> str:
    return " ".join(value.strip().lower().replace("_", " ").split())


def _family_alias_matches(key: str, alias: str) -> bool:
    normalized = _normalize_family_name(alias)
    return bool(normalized) and (key == normalized or normalized in key)


def _explicit_failure_type(text: str) -> str | None:
    marker = "failure_type="
    if marker not in text:
        return None
    tail = text.split(marker, 1)[1]
    value: list[str] = []
    for char in tail:
        if char.islower() or char == "_":
            value.append(char)
        else:
            break
    return "".join(value) or None
